---
# Service to receive logs at input point of ltr

apiVersion: v1
kind: Service
metadata:
  name: prom-service
spec:
  type: LoadBalancer
  ports:
    - port: 31909
      targetPort: 9090
      name: ltr-input-service
  selector:
    app: prometheus
    component: server
