# The Punchplatform code is licensed under the outer restricted Tiss license:
#
#   Copyright © [2014]-[2018] Thales Services
#
#   Licensed under the Thales Inner Source Software License
#   (Version 1.0, InnerPublic - OuterRestricted the "License");
#   You may not use this file except in compliance with the License.
#
#   You may obtain a copy of the License at https://ecm.corp.thales/Livelink/livelink.exe?func=ll&objId=126019196&objAction=browse&viewType=1
#
#   See the License for the specific language governing permissions and limitations
#   under the License.

# -----------------------------------------------------------------------------------
# GLOBAL CONFIGURATION
# -----------------------------------------------------------------------------------

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_CLEAN_FLAGS: -ffdx -e .build/
  TZ: "Europe/Paris"
  # for helm download
  VERIFY_CHECKSUM: "false"
  CLUSTER_NAME: punchplatform-${CI_PIPELINE_ID}
cache: {}

services:
  - docker:19.03.13-dind

stages:
  - make-start
  
# -----------------------------------------------------------------------------------
# JOBS
# -----------------------------------------------------------------------------------

###########
## MAKE ##
###########

make-start:
  image: docker:19.03.13
  stage: make-start
  tags:
    - docker-runner
  script:
    - apk update
    - apk add bash make curl unzip jq gettext sudo
    - bash -c "make clean CLUSTER_NAME=${CLUSTER_NAME};"
    - . bin/gitlab/kubectl.sh
    - bash -c "make CLUSTER_NAME=${CLUSTER_NAME} CI=true start; make CLUSTER_NAME=${CLUSTER_NAME} CI=true clean;"
