# -----------------------------------------------------------------------------------
# GLOBAL CONFIGURATION
# -----------------------------------------------------------------------------------

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_CLEAN_FLAGS: -ffdx -e .build/
  TZ: "Europe/Paris"
  # for helm download
  VERIFY_CHECKSUM: "false"
  CLUSTER_NAME: punchplatform-${CI_PIPELINE_ID}
cache: {}

services:
  - docker:19.03.13-dind

stages:
  - make-start
  - sync-repo
  
# -----------------------------------------------------------------------------------
# JOBS
# -----------------------------------------------------------------------------------

###########
## MAKE ##
###########

make-start:
  image: docker:19.03.13
  stage: make-start
  retry: 1
  tags:
    - docker-runner
  before_script:
    - apk update
    - apk add bash make curl unzip jq gettext sudo
  script:
    - bash -c "make clean CLUSTER_NAME=${CLUSTER_NAME};"
    - . bin/gitlab/kubectl.sh
    - bash -c "make CLUSTER_NAME=${CLUSTER_NAME} CI=true start; make CLUSTER_NAME=${CLUSTER_NAME} CI=true clean;"

Sync Github:
  image: alpine:3.15
  stage: sync-repo
  retry: 1
  tags: 
    - docker-runner
  before_script:
    - apk update
    - apk add git
  script:
    - git remote add github https://${PUNCH_GITHUB_USER}:${PUNCH_GITHUB_TOKEN}@github.com/punchplatform/kooker.git || true
    - git push github HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
