apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamJavaPunchline
metadata:
   name: lmc-archiving
   annotations:
      prometheus.io/scrape: true
      prometheus.io/port: '7774'
spec:
   image: ghcr.io/punchplatform/punchline-java:8.0-dev
   dependencies:
   - punch-parsers:org.thales.punch:punch-common-punchlets:1.1.0
   env:
   -  name: JDK_JAVA_OPTIONS
      value: -Xms100m -Xmx450m
      exit_conditions: null
   dag:
   -  id: input
      kind: source
      type: kafka_source
      load_control:
         throughput: 100000
         max_pending_row_number: 10000
         row_timeout_secs: 0
      settings:
         bootstrap.servers: kafka-kafka-bootstrap.processing:9092
         topics: ref-test-01-lmr
         value.format: lumberjack
         start_offset_strategy: last_committed
      out:
      -  id: archive_sink
         table: logs
         columns:
         -  name: log
            type: string
         -  name: _ppf_partition_id
            type: long
         -  name: _ppf_partition_offset
            type: long
         -  name: _ppf_remote_host
            type: string
         -  name: _ppf_remote_port
            type: int
         -  name: _ppf_local_host
            type: string
         -  name: _ppf_local_port
            type: int
         -  name: _ppf_timestamp
            type: string
         -  name: _ppf_id
            type: string
   -  id: archive_sink
      type: archive_sink
      kind: function
      settings:
         create_root: true
         strategy: at_least_once
         destination: file:///tmp/archive-logs/storage
         file_prefix_pattern: '%{topic}/%{partition}/%{date}/puncharchive-%{node_id}-%{partition}-%{offset}-%{tags}'
         pool: mypool
         topic: mytopic
         compression_format: GZIP
         timestamp_column: _ppf_timestamp
         batch_size: 1000
         batch_expiration_timeout: 10s
      out:
      -  id: metadata_sink
         table: logs
         columns:
         - name: metadata
           type: string
   -  id: metadata_sink
      type: elasticsearch_sink
      kind: function
      settings:
         http_hosts:
         -  host: localhost
            port: 9200
         batch_interval: 0
         batch_size: 1
         request_timeout: 20s
         index_type: daily
         index_prefix: testv7-metadata-
         document_json_column: metadata
         bulk_failure_action: fail
         document_failure_action: fail