apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: Punchline
metadata:
  name: sample-stormline
  labels:
    channel: test
    tenant: test
spec:
  exit_conditions:
    success:
      acks_greater_or_equal_to: -1
      require_no_remaining_row_to_inject: true
      require_no_pending_row: true
    failure:
      fails_greater_or_equal_to: 1
  image: ghcr.io/punchplatform/punchline-java:8.0-dev
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-Xms100m -Xmx450m"
  dag:
    - id: input
      type: extraction_input
      kind: source
      load_control:
        auto_monitoring_period_secs: 10
        throughput: 0
        max_pending_row_number: 10000
        row_timeout_secs: 30
      settings:
        elastic_settings:
          es.scroll: true
          es.scroll.size: 10000
          es.scroll.keepalive: 10m
        http_hosts:
          - host: 127.0.0.1
            port: 9200
        index: testv7-metadata-2022.01.26
        query: "{\n  \"query\": {\n    \"match_all\": {}\n  }\n}"
        mode: raw
      out:
        - id: print
          table: logs
          columns:
            - name: response
              type: string
    - id: print
      type: punchlet_function
      kind: function
      settings:
        punchlet_code: "{print(root);}"