{
 "title": "[Applications Monitoring] Ack Fail Rates Dashboard",
 "tags": [
  "punch",
  "monitoring",
  "eps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\"}"
    }
   },
   {
    "name": "cpt",
    "label": "Node",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\",app_name=~\"${app}\"}"
    }
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Acks/Fails per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_name,namespace,node_id)(rate(punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}[$__rate_interval]))",
     "legendFormat": "Acks : {{namespace}} - {{app_name}} - {{node_id}}"
    },
    {
     "expr": "sum by (app_name,namespace,node_id)(rate(punchline_dag_node_row_failed_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}[$__rate_interval]))",
     "legendFormat": "Fails : {{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "FAIL Rate (Max)",
   "type": "stat",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app_name,namespace) (rate(punchline_dag_node_row_failed_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} - {{app_name}}"
    }
   ]
  },
  {
   "title": "ACK Rate (Max)",
   "type": "stat",
   "gridPos": { "h": 20, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app_name,namespace) (rate(punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} - {{app_name}}"
    }
   ]
  },
  {
   "title": "Fails and Acks / Component",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "punchline_dag_node_row_failed_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}"
    },
    {
     "expr": "punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}"
    }
   ]
  }
 ]
}