{
 "title": "[Applications Monitoring] Advanced insights",
 "tags": [
  "punch",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\"}"
    }
   },
   {
    "name": "cpt",
    "label": "Node",
    "query": {
     "query": "punchline_dag_node_row_acked_num_total{namespace=~\"${ns}\",app_name=~\"${app}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "punchline_dag_node_cpu_time_ns_sum{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"} / punchline_dag_node_cpu_time_ns_count{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Pending Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "punchline_dag_node_row_pending_num{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Traversal Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "punchline_dag_node_row_traversal_time_ms_sum{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"} / punchline_dag_node_row_traversal_time_ms_count{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "CPU Time (Max)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app_name,namespace,node_id) (punchline_dag_node_cpu_time_ns_sum{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"} / punchline_dag_node_cpu_time_ns_count{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"})",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Pending Rows",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "punchline_dag_node_row_pending_num{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"}",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Traversal Time (Max)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (app_name,namespace,node_id) (punchline_dag_node_row_traversal_time_ms_sum{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"} / punchline_dag_node_row_traversal_time_ms_count{namespace=~\"${ns}\",app_name=~\"${app}\",node_id=~\"${cpt}\"})",
     "legendFormat": "{{namespace}} - {{app_name}} - {{node_id}}"
    }
   ]
  }
 ]
}