---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ref-test-01-ltr
  namespace: processing
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ref-test-01-lmr
  namespace: processing
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1


