apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: lmc-elasticsearch
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: '7773'     
     platform.gitlab.thalesdigital.io/platform: platform
spec:  
  image: ghcr.io/punchplatform/punchline-java:8.0-dev
  dependencies:
  - punch-parsers:org.thales.punch:punch-common-punchlets:1.0.2
  env:
  - name: JDK_JAVA_OPTIONS
    value: "-Xms100m -Xmx450m"
    exit_conditions:
  dag:
  - id: input
    kind: source
    type: kafka_source
    load_control:
      throughput: 100
      max_pending_row_number: 1000
      row_timeout_secs: 30
    settings:
      bootstrap.servers: kafka-kafka-bootstrap.processing:9092
      topics: ref-test-01-lmr
      value.format: lumberjack
      start_offset_strategy: last_committed
    out: 
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
      - name: _ppf_remote_host
        type: string
      - name: _ppf_remote_port
        type: int
      - name: _ppf_local_host
        type: string
      - name: _ppf_local_port
        type: int
      - name: _ppf_timestamp
        type: string
      - name: _ppf_id      
        type: string
  - id: parser
    type: punchlet_function
    kind: function 
    settings:
      punchlet_code: "{ print(root); }"
 