---
# Service to receive logs at input point of ltr

apiVersion: v1
kind: Service
metadata:
  name: ltr-input-service
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: '7770'     
spec:
  type: LoadBalancer
  ports:
    - port: 31880
      targetPort: 8880
      name: ltr-input-service
  selector:
    punchline-name: ltr-in
