---
apiVersion: scheduler.gitlab.thalesdigital.io/v1
kind: Plan
metadata:
  name: plan-spark-sample
spec:
  apiVersion: punchline.gitlab.thalesdigital.io/v1
  kind: Sparkline
  # note: specifying cron and interval will result in cron overriding interval
  # only interval or cron should be set at a time
  #interval: 10s
  cron: "* * * * *"
  dates:
    from:
      offset: "-10h45m"
      format: "2006-01-02T15:04:05-0700"
    to:
      offset: "10h45m"
      format: "2006-01-02T15:04:05-0700"
  templateSpec:
    image: ghcr.io/punchplatform/sparkline:7.0.1-SNAPSHOT
    imagePullPolicy: IfNotPresent
    serviceAccount: admin-user
    dependencies:
    - punch-parsers:com.mycompany:test-parsers:1.0.0
    garbageCollect: false
    resources:
      limits:
        cpu: "200m"
        memory: "2Gi"
      requests:
        cpu: "100m"
        memory: "1Gi"
    initContainerImage: ghcr.io/punchplatform/resourcectl:7.0.1-SNAPSHOT
    implementation: java
    settings:
      spark.executor.instances: "1"
      spark.kubernetes.authenticate.driver.serviceAccountName: admin-user
    punchline:
      dag:
      - settings:
          input_data:
          - date: "{{ .from }}"
            name: from_date
          - date: "{{ .to }}"
            name: to_date
        component: input
        publish:
        - stream: data
        type: dataset_generator
      - settings:
          truncate: false
        component: show
        subscribe:
        - component: input
          stream: data
        type: show