---
apiVersion: punchline.punchplatform.io/v2
kind: StreamPunchline
metadata:
  name: punchline-with-resource-example
  annotations:
    punchplatform.io/platform: platform
spec: 
  containers:
    applicationContainer:
      image: ghcr.io/punchplatform/punchline-java:8.0-dev
      imagePullPolicy: IfNotPresent
      env:
      - name: JDK_JAVA_OPTIONS
        value: "-Xms100m -Xmx450m"
  dependencies:
  - punch-parsers:com.mycompany:test-parsers:1.0.0
  dag:
  - id: generator
    kind: source
    type: generator_source
    settings:
      messages:
      - color=green city=Paris uri=https://punchplatform.com
      - color=yellow city=New York uri=https://punchplatform.com
      - color=red city=London uri=https://punchplatform.com
    out:
      - id: punchlet
        table: logs
        columns:
          - name: data
            type: string
  - id: punchlet
    kind: function
    type: punchlet_function
    settings:
      resources:
        - name: custom_groks
          url: com/mycompany/sample/groks/pattern.grok
          type: file
          format: grok
        - name: color_codes 
          url: com/mycompany/sample/resources/color_codes.json
          type: file
          format: json
      punchlets:
        - com/mycompany/sample/parser.punch
        - com/mycompany/sample/enrich.punch
    out:
      - id: printer
        table: logs
        columns:
          - name: data
          - name: log
  - id: printer
    kind: function
    type: punchlet_function
    settings:
      punchlet_code: "{print(root);}"
      