---
apiVersion: punchline.gitlab.thalesdigital.io/v1
kind: Sparkline
metadata:
  name: java-sample
spec:
  image: ghcr.io/punchplatform/sparkline:7.0.1-SNAPSHOT
  imagePullPolicy: IfNotPresent
  serviceAccount: admin-user
  garbageCollect: false
  initContainerImage: ghcr.io/punchplatform/resourcectl:7.0.1-SNAPSHOT
  implementation: java
  settings:
    spark.executor.instances: "1"
    spark.kubernetes.authenticate.driver.serviceAccountName: admin-user
  punchline:
    dag:
    - settings:
        input_data:
        - date: "{{ from }}"
          name: from_date
        - date: "{{ to }}"
          name: to_date
      component: input
      publish:
      - stream: data
      type: dataset_generator
    - settings:
        truncate: false
      component: show
      subscribe:
      - component: input
        stream: data
      type: show
