---
apiVersion: punchline.gitlab.thalesdigital.io/v1
kind: Stormline
metadata:
  name: stormline-resource-sample
  annotations:
    platform.gitlab.thalesdigital.io/platform: platform
spec:  
  image: ghcr.io/punchplatform/stormline:7.0.1-SNAPSHOT
  imagePullPolicy: IfNotPresent
  serviceAccount: admin-user
  dependencies:
  - punch-parsers:com.mycompany:test-parsers:1.0.0
  env:
  - name: JDK_JAVA_OPTIONS
    value: "-Xms100m -Xmx450m"
  punchline:
    dag:
    - type: generator_input
      component: generator
      settings:
        messages:
        - my first log
        - My second message log
        - And finally a third one
      publish:
      - stream: logs
        fields:
        - log
    - type: punchlet_node
      component: processing
      settings:
        punchlet_grok_pattern_dirs:
          - com/mycompany/sample/groks
        punchlet_json_resources:
          - com/mycompany/sample/resources/color_codes.json
        punchlets:
          - com/mycompany/sample/parser.punch
      subscribe:
      - stream: logs
        component: generator