---
apiVersion: punchline.gitlab.thalesdigital.io/v1
kind: Stormline
metadata:
  name: stormline-sample
spec:  
  image: ghcr.io/punchplatform/stormline:7.0.1-SNAPSHOT
  imagePullPolicy: IfNotPresent
  env:
  - name: JDK_JAVA_OPTIONS
    value: "-Xms100m -Xmx450m"
  punchline:
    dag:
    - type: generator_input
      component: generator
      settings:
        messages:
        - my first log
        - My second message log
        - And finally a third one
      publish:
      - stream: logs
        fields:
        - log
    - type: punchlet_node
      component: processing
      settings:
        punchlet_code: "{ print(root); }"
      subscribe:
      - stream: logs
        component: generator