apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: ltr-in
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: '7770'     
     punch/platform: main

spec: #StreamPunchlineSpec

  containers:
    serviceAccount: admin
    affinity:
      XXXX
    resourcesInitContainer: 
      image:
      imagePullPolicy:
      resourcesProviderUrl: http://artifacts-service.punch-system:4245
      trustSelfSignedCertificates: true 
      debug: false
    applicationContainer:
      resourcesRequest: ? type Kube
        cpu:
        ram:
      image: ghcr.io/punchplatform/punchline-java:8.0-dev
      imagePullPolicy: 
      env:
        - name: JDK_JAVA_OPTIONS
          value: '-Xms100m -Xmx450m'
      configMapMounts:
        - name: resolver
          mountPath: /opt/punch/resolver

  job: // Paramètres de job  , pour un BatchPunchline ou BatchApplication seulement
    backoff-limit
    max-retries

  
  engineSettings:
    punchlightTopoEngine:
      max_rows_pending: 10000
      row_timeout: 30s
      max_threads: 4
      otherSettings:
      key: value
    Spark:
       max_workers: 2
    Flink:


  dependencies:
      - xxxx
      - yyyy

  dag:
    - id: input
      kind: source
      type: syslog_source
      load_control:
        throughput: 100000
        max_pending_row_number: 10000
        row_timeout_secs: 0
      settings:
        proto: tcp
        host: 0.0.0.0
        port: 8880
        delimiter: eol
      out: 
      - id: output
        table: logs
        columns: 
        - name: log
          type: string
        - name: _ppf_remote_host
          type: string
        - name: _ppf_remote_port
          type: int
        - name: _ppf_local_host
          type: string
        - name: _ppf_local_port
          type: int
        - name: _ppf_timestamp
          type: long
        - name: _ppf_id      
          type: string
      - id: processing
        table: logs
        columns: 
        - name: log
          type: string
        - name: _ppf_remote_host
          type: string
        - name: _ppf_remote_port
          type: int
        - name: _ppf_local_host
          type: string
        - name: _ppf_local_port
          type: int
        - name: _ppf_timestamp
          type: long
        - name: _ppf_id      
          type: string
    - id: output
      kind: sink
      type: kafka_sink
      settings:
        format: lumberjack
        producer.acks: all
        producer.batch.size: 16384
        producer.linger.ms: 5
        bootstrap.servers: kafka-kafka-bootstrap.processing:9092
        topic: ref-test-01-ltr
    - id: processing
      type: punchlet_function
      kind: function 
      settings:
        punchlet_code: "{ print(root); }"
    
