apiVersion: punchline.gitlab.thalesdigital.io/v2
kind: StreamPunchline
metadata:
  name: generator-to-es
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '7773'     
spec:  
  image: ghcr.io/punchplatform/punchline-java:8.0-dev
  env:
  - name: JDK_JAVA_OPTIONS
    value: "-Xms100m -Xmx450m"
  dag:
  - id: input
    kind: source
    type: generator_source
    settings:
      messages:
      - "my first log"
      - "My second message log"
      - "And finally a third one"
    out:
    - id: parser
      table: logs
      columns:
      - name: log
        type: string
  - id: parser
    kind: function
    type: punchlet_function
    settings:
       punchlet_code: "{[logs][log][message]=[logs][log]; [logs][log][hello]=42;print(root);}"
    out:
    - id: elasticsearch_sink
      table: logs
      columns:
      - name: log
        type: string

  - id: elasticsearch_sink
    type: elasticsearch_sink
    kind: function
    settings:
      http_hosts: 
      - host: localhost
        port: 9200

      batch_interval: 5000
      batch_size: 1
      request_timeout: 20s
      index_type: daily
      index_prefix: debug
      document_json_column: log
      extra_fields:
      - type: date
        document_field: '@timestamp'
        format: iso
      bulk_failure_action: fail
      document_failure_action: forward_all 