{
 "title": "PunchOperator",
 "description": "Monitor PunchOperator controllers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(metadata_namespace)"
    }
   },
   { "name": "Platform", "label": "Platform", "query": { "query": "label_values(platform)" } },
   { "name": "Punchline", "label": "Punchline", "query": { "query": "label_values(spec_kind)" } },
   { "name": "PlanId", "label": "PlanId", "query": { "query": "label_values(metadata_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Plan Scheduler Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plan_scheduler_uptime_sec_count"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "plan_scheduler_last_succeeded_schedule_timestamp_sec_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}*1000"
    },
    {
     "expr": "plan_scheduler_iteration_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}"
    },
    {
     "expr": "plan_scheduler_next_schedule_timestamp_sec_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}*1000"
    },
    {
     "expr": "plan_scheduler_previous_schedule_endtime_timestamp_sec_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}*1000"
    },
    {
     "expr": "plan_scheduler_previous_schedule_timestamp_sec_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}*1000"
    },
    {
     "expr": "plan_scheduler_current_schedule_timestamp_sec_total{previous_schedule_status!=\"\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}*1000"
    }
   ]
  },
  {
   "title": "Plan Previous Schedule AVG Elasped Time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (metadata_name) (avg_over_time(plan_scheduler_previous_elapsed_time_by_iteration_timestamp_sec_sum{metadata_name=~\"$PlanId\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\"}[$__rate_interval])/plan_scheduler_previous_elapsed_time_by_iteration_timestamp_sec_count{metadata_name=~\"$PlanId\",metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\"})",
     "legendFormat": "{{PlanId}}"
    }
   ]
  },
  {
   "title": "List of Plan Current Schedules retries",
   "type": "table",
   "description": "Plan current schedule retries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "plan_current_schedule_retries_count{metadata_namespace=~\"$Namespace\",platform=~\"$Platform\",spec_kind=~\"$Punchline\",metadata_name=~\"$PlanId\"}"
    }
   ]
  },
  {
   "title": "Operator(s) Work Load / Work Queue Add Rate | Total number of adds handled by workqueue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"punchoperator-metrics-service\"}[5m])) by (name)"
    }
   ]
  },
  {
   "title": "Work Queue Depth | Current depth of workqueues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"punchoperator-metrics-service\"}[5m])) by (name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency | How long in seconds an item stays in workqueue before being requested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"punchoperator-metrics-service\"}[5m])) by (name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Operators HTP Status Code Requests Rate",
   "type": "graph",
   "description": "Sparkline,Flinkline,Stormline,Application 2XX,3XX,4XX,5XX http requests rate",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"punchoperator-metrics-service\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"punchoperator-metrics-service\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"punchoperator-metrics-service\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"punchoperator-metrics-service\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "GO RAM Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"punchoperator-metrics-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GO CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"punchoperator-metrics-service\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GO Concurrent Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"punchoperator-metrics-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}